### ISSUE TITLE
Phase P03 — Legal Action Validation

### ISSUE THREAD

**Issue by sgoxel** [sgoxel/The_Advisor_Game#39]
Planner-owned active-phase tracker activated only after dedicated Tester `PHASE/RELEASE PASS — P02 Stage 2` for `v0.2.0-dev.1` at exact commit `bb7dc08ff560efa8eef2c5e54f1531325707183f`.

Goal: establish a deterministic, simulation-owned legality boundary for candidate character actions before consequences are resolved, while preserving the core rule **Player advises → AI Character decides → Simulation validates → World reacts**.

Scope / phase boundary:
- Define and implement legal-action request/result contracts below README authority.
- Validate actor authority/capability and explicit authoritative-state preconditions.
- Compose deterministic legality decisions with stable, human-readable reasons.
- Reject caller attempts to force legality, bypass authority, or inject authoritative outcomes.
- Expose a narrowly bounded public legality-inspection flow for manual verification without giving the player binding control over the protagonist.
- Preserve verified P01 save/import/export behavior and P02 deterministic seeded-check behavior.
- Do not implement P04 autonomous Local BOT decision-making, future progression systems, world generation, or action consequence resolution merely because legality validation will later support them.

Release gate:
- P03 tasks complete in Planner dependency order.
- Required Coder and Graphic Designer issues receive independent Tester PASS evidence.
- Legal-action decisions are deterministic from explicit authoritative inputs and remain simulation-owned.
- UI/player input cannot force a legal/illegal result or directly execute/commit a character action.
- Cumulative P01/P02 behavior remains green.
- Public legality inspection is responsive and accessible on representative desktop/tablet/phone layouts.
- Exact candidate passes unit/regression, Browser Tests, responsive Playwright/axe, and Lighthouse as applicable.
- Dedicated Tester completes the two-stage Verified Release process and exact live Pages/release verification before P04 may activate.

Subtasks are tracked in `TODO.json`. README is protected and is not modified by this activation.

**Comment by sgoxel** [comment]
Planner Worker — P03 activation audit

Purpose:
- Activate the oldest unfinished phase only after dedicated Tester completed `PHASE/RELEASE PASS — P02 Stage 2` and create a granular, role-balanced P03 backlog under current README authority.

Release prerequisite verified:
- P02 exact verified candidate: `bb7dc08ff560efa8eef2c5e54f1531325707183f`.
- Release: `v0.2.0-dev.1` — `Phase 2 — Seeded Checks and RNG Contract`, GitHub Release ID `378007272`.
- Dedicated Tester evidence on #26 records Stage 1 exact-candidate Tests/Browser Tests/Playwright/Lighthouse PASS, autonomous Verified Release run `33098967510` SUCCESS, exact Pages SHA-marker verification, live Playwright/axe 28/28 PASS, and final `PHASE/RELEASE PASS — P02 Stage 2`.
- P02 parent #20 and release gate #26 are closed completed.

Planning changes:
- `ROADMAP.json` commit `c6ca4ed893e3f39a43b2b1dde78b77fdf2c00911`: P02 -> completed with exact release evidence; P03 -> sole active phase; P04+ remain planned/inactive.
- `TODO.json` initial P03 graph commit `d846ff6ee60394c51e78c73b5f0e661d457547d6`.
- `TODO.json` follow-up commit `fa3190b4e0fb50867c911b8718a02aff2aada2b8`: removed an unnecessary startup dependency so Graphic Designer #43 can proceed in parallel with Coder #40.
- Current verified planning blobs: ROADMAP `761272e4223f5bd5171185c67293ff70d3396f16`; TODO `8b05ca3e686ce62cb1daf466f6461a448cb6dc89`.

P03 decomposition / routing:
- #40 P03-T01 — validation contract/reason taxonomy — Coder.
- #41 P03-T02 — actor authority/capability rules — Coder, after #40.
- #42 P03-T03 — authoritative-state preconditions — Coder, after #40; parallel with #41.
- #43 P03-T04 — legal-action feedback/explanation visual system — Graphic Designer; immediately eligible in parallel with #40.
- #44 P03-T05 — composed authoritative validator — Coder after #41/#42.
- #45 P03-T06 — legality/bypass regression — Coder after #44.
- #46 P03-T07 — public legality-inspection integration — Coder after #43/#44.
- #47 P03-T08 — post-integration visual refinement — Graphic Designer after #46.
- #48 P03-T09 — cumulative P01/P02 compatibility regression — Coder after #46.
- #49 P03-T10 — final responsive/browser/accessibility regression — Coder after #45/#47/#48.
- #50 P03-T11 — dedicated Tester two-stage release gate; depends on all required P03 implementation/design work.

Scope boundaries:
- P03 validates candidate-action legality only; it does not implement P04 autonomous BOT choice, direct player action control, action consequence resolution, future progression, or world generation.
- Player/UI cannot force legality, fabricate authority/preconditions, or directly execute/commit the protagonist's action.
- P01/P02 cumulative verified behavior remains protected.
- Two focused Graphic Designer tasks are included (#43 and #47), each independently testable before release.

Checks/result:
- Protected `README.md` was read first and not modified.
- Re-fetched committed ROADMAP/TODO after writes; both are valid Planner-owned active-P03 records.
- Re-searched open P03 issues; #39–#50 exist with expected role/dependency metadata.
- Immediate eligible unclaimed work at end of this run: Coder #40 and Graphic Designer #43.
- P04 remains inactive.

Public-state risk note:
- `main` has advanced past released P02 only through Planner planning commits; the verified public product remains the exact `v0.2.0-dev.1` release until a future P03 candidate independently passes the release workflow.

Next:
- Coder claims #40.
- Graphic Designer may claim #43 concurrently.
- After #40 closes, #41 and #42 become parallel Coder work for Coder #1/#2.
